name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: nitishchy12
          github_user_email: nitishchy32@gmail.com
          output_file: github-contribution-grid-snake.svg
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "🐍 Generate new snake animation"
          add: github-contribution-grid-snake.svg
